before:
  hooks:
    - go mod tidy

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/conventionalcommit/commitlint/config.version={{.Version}} -X github.com/conventionalcommit/commitlint/config.commit={{.FullCommit}} -X github.com/conventionalcommit/commitlint/config.buildTime={{.Date}}
    ignore:
      - goos: darwin
        goarch: arm64

archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^style:'
      - '^chore:'
      - '^refactor:'
      - '^build:'
      - '^ci:'

release:
  draft: true
